import Foundation
import ZEUVECore
import ZEUVEStorage
import ZEUVEOperations
public final class CleanerUndoService:@unchecked Sendable{
    let coordinator:OperationCoordinator;let repository:CleanerRepository;let history:HistoryRepository;let mutator:any CleanerFileMutating;let fileManager:FileManager
    public init(coordinator:OperationCoordinator,repository:CleanerRepository,history:HistoryRepository,mutator:any CleanerFileMutating=SystemCleanerFileMutator(),fileManager:FileManager = .default){self.coordinator=coordinator;self.repository=repository;self.history=history;self.mutator=mutator;self.fileManager=fileManager}
    public func undo(historyID:UUID)async throws->CleanerExecutionSummary{let op=try await coordinator.begin(moduleID:cleanerModuleIdentifier,name:"Restaurando desde la Papelera");var results:[CleanerItemExecutionResult]=[];do{let items=try repository.undoItems(historyID:historyID);for x in items{if await coordinator.shouldCancel(id:op){break};guard !fileManager.fileExists(atPath:x.originalURL.path) else{results.append(.init(sourcePath:x.originalURL.path,trashPath:x.trashURL.path,status:.restoreConflict,message:"La ubicación original ya está ocupada."));continue};guard let current=CleanerFileInspection.fingerprint(at:x.trashURL,fileManager:fileManager),current==x.fingerprint else{results.append(.init(sourcePath:x.originalURL.path,trashPath:x.trashURL.path,status:.unavailable,message:"El elemento de la Papelera ya no está disponible o cambió."));continue};do{try mutator.restore(x.trashURL,to:x.originalURL);try repository.removeUndoItem(id:x.id);results.append(.init(sourcePath:x.originalURL.path,status:.restored))}catch{results.append(.init(sourcePath:x.originalURL.path,trashPath:x.trashURL.path,status:.failed,message:error.localizedDescription))}}
        let remaining=try repository.undoItems(historyID:historyID);let restored=results.filter{$0.status == .restored}.count;let status:OperationStatus = remaining.isEmpty ? .undone:(restored>0 ? .partiallyUndone:.undoUnavailable);try history.updateUndoState(id:historyID,status:status,undoAvailable:!remaining.isEmpty);try await coordinator.finish(id:op);return .init(results:results,deletedLogicalBytes:0,deletionMode:.trash)}catch{try? await coordinator.finish(id:op);throw error}}
}
