#!/usr/bin/env python3
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / "ZEUVE.xcodeproj" / "project.pbxproj"
APP_ROOT = ROOT / "Sources" / "ZEUVEApp"
source_files = sorted(p.relative_to(APP_ROOT).as_posix() for p in APP_ROOT.rglob("*.swift"))

def uid(value: str) -> str:
    return hashlib.sha1(value.encode()).hexdigest().upper()[:24]

project_id = uid("project")
main_group = uid("main-group")
app_group = uid("app-group")
products_group = uid("products-group")
target_id = uid("target")
product_ref = uid("product-ref")
sources_phase = uid("sources-phase")
frameworks_phase = uid("frameworks-phase")
resources_phase = uid("resources-phase")
sign_engines_phase = uid("sign-engines-phase")
engines_ref = uid("engines-ref")
engines_build = uid("engines-build")
project_config_list = uid("project-config-list")
target_config_list = uid("target-config-list")
project_debug = uid("project-debug")
project_release = uid("project-release")
target_debug = uid("target-debug")
target_release = uid("target-release")
package_ref = uid("package-ref")

products = ["ZEUVECore", "ZEUVEStorage", "ZEUVEOperations", "ZEUVEEngines", "OrganizerModule", "YouTubeDownloaderModule", "ChatAnalyzerModule", "UniversalConverterModule"]
product_deps = {name: uid(f"product-dep-{name}") for name in products}
framework_builds = {name: uid(f"framework-build-{name}") for name in products}
file_refs = {path: uid(f"file-ref-{path}") for path in source_files}
build_files = {path: uid(f"build-file-{path}") for path in source_files}

lines = []
a = lines.append
a("// !$*UTF8*$!")
a("{")
a("\tarchiveVersion = 1;")
a("\tclasses = {};")
a("\tobjectVersion = 60;")
a("\tobjects = {")

a("\n/* Begin PBXBuildFile section */")
a(f"\t\t{engines_build} /* Engines in Resources */ = {{isa = PBXBuildFile; fileRef = {engines_ref} /* Engines */; }};")
for path in source_files:
    a(f"\t\t{build_files[path]} /* {Path(path).name} in Sources */ = {{isa = PBXBuildFile; fileRef = {file_refs[path]} /* {Path(path).name} */; }};")
for name in products:
    a(f"\t\t{framework_builds[name]} /* {name} in Frameworks */ = {{isa = PBXBuildFile; productRef = {product_deps[name]} /* {name} */; }};")
a("/* End PBXBuildFile section */\n")

a("/* Begin PBXFileReference section */")
for path in source_files:
    a(f"\t\t{file_refs[path]} /* {Path(path).name} */ = {{isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = \"{path}\"; sourceTree = \"<group>\"; }};")
a(f"\t\t{product_ref} /* ZEUVE.app */ = {{isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = ZEUVE.app; sourceTree = BUILT_PRODUCTS_DIR; }};")
a(f"\t\t{engines_ref} /* Engines */ = {{isa = PBXFileReference; lastKnownFileType = folder; path = Resources/Engines; sourceTree = SOURCE_ROOT; }};")
a("/* End PBXFileReference section */\n")

a("/* Begin PBXFrameworksBuildPhase section */")
a(f"\t\t{frameworks_phase} /* Frameworks */ = {{")
a("\t\t\tisa = PBXFrameworksBuildPhase;")
a("\t\t\tbuildActionMask = 2147483647;")
a("\t\t\tfiles = (")
for name in products:
    a(f"\t\t\t\t{framework_builds[name]} /* {name} in Frameworks */,")
a("\t\t\t);")
a("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
a("\t\t};")
a("/* End PBXFrameworksBuildPhase section */\n")

a("/* Begin PBXGroup section */")
a(f"\t\t{main_group} = {{")
a("\t\t\tisa = PBXGroup;")
a("\t\t\tchildren = (")
a(f"\t\t\t\t{app_group} /* App */,")
a(f"\t\t\t\t{products_group} /* Products */,")
a(f"\t\t\t\t{engines_ref} /* Engines */,")
a("\t\t\t);")
a("\t\t\tsourceTree = \"<group>\";")
a("\t\t};")
a(f"\t\t{app_group} /* App */ = {{")
a("\t\t\tisa = PBXGroup;")
a("\t\t\tchildren = (")
for path in source_files:
    a(f"\t\t\t\t{file_refs[path]} /* {Path(path).name} */,")
a("\t\t\t);")
a("\t\t\tname = App;")
a("\t\t\tpath = Sources/ZEUVEApp;")
a("\t\t\tsourceTree = SOURCE_ROOT;")
a("\t\t};")
a(f"\t\t{products_group} /* Products */ = {{")
a("\t\t\tisa = PBXGroup;")
a("\t\t\tchildren = (")
a(f"\t\t\t\t{product_ref} /* ZEUVE.app */,")
a("\t\t\t);")
a("\t\t\tname = Products;")
a("\t\t\tsourceTree = \"<group>\";")
a("\t\t};")
a("/* End PBXGroup section */\n")

a("/* Begin PBXNativeTarget section */")
a(f"\t\t{target_id} /* ZEUVE */ = {{")
a("\t\t\tisa = PBXNativeTarget;")
a(f"\t\t\tbuildConfigurationList = {target_config_list} /* Build configuration list for PBXNativeTarget \"ZEUVE\" */;")
a("\t\t\tbuildPhases = (")
a(f"\t\t\t\t{sources_phase} /* Sources */,")
a(f"\t\t\t\t{frameworks_phase} /* Frameworks */,")
a(f"\t\t\t\t{resources_phase} /* Resources */,")
a(f"\t\t\t\t{sign_engines_phase} /* Firmar motores incluidos */,")
a("\t\t\t);")
a("\t\t\tbuildRules = ();")
a("\t\t\tdependencies = ();")
a("\t\t\tname = ZEUVE;")
a("\t\t\tpackageProductDependencies = (")
for name in products:
    a(f"\t\t\t\t{product_deps[name]} /* {name} */,")
a("\t\t\t);")
a("\t\t\tproductName = ZEUVE;")
a(f"\t\t\tproductReference = {product_ref} /* ZEUVE.app */;")
a("\t\t\tproductType = \"com.apple.product-type.application\";")
a("\t\t};")
a("/* End PBXNativeTarget section */\n")

a("/* Begin PBXProject section */")
a(f"\t\t{project_id} /* Project object */ = {{")
a("\t\t\tisa = PBXProject;")
a("\t\t\tattributes = {")
a("\t\t\t\tBuildIndependentTargetsInParallel = 1;")
a("\t\t\t\tLastSwiftUpdateCheck = 1600;")
a("\t\t\t\tLastUpgradeCheck = 1600;")
a("\t\t\t\tTargetAttributes = {")
a(f"\t\t\t\t\t{target_id} = {{ CreatedOnToolsVersion = 16.0; }};")
a("\t\t\t\t};")
a("\t\t\t};")
a(f"\t\t\tbuildConfigurationList = {project_config_list} /* Build configuration list for PBXProject \"ZEUVE\" */;")
a("\t\t\tcompatibilityVersion = \"Xcode 15.0\";")
a("\t\t\tdevelopmentRegion = es;")
a("\t\t\thasScannedForEncodings = 0;")
a("\t\t\tknownRegions = (es, Base);")
a(f"\t\t\tmainGroup = {main_group};")
a(f"\t\t\tpackageReferences = ({package_ref} /* XCLocalSwiftPackageReference \".\" */);")
a(f"\t\t\tproductRefGroup = {products_group} /* Products */;")
a("\t\t\tprojectDirPath = \"\";")
a("\t\t\tprojectRoot = \"\";")
a("\t\t\ttargets = (")
a(f"\t\t\t\t{target_id} /* ZEUVE */,")
a("\t\t\t);")
a("\t\t};")
a("/* End PBXProject section */\n")

a("/* Begin PBXResourcesBuildPhase section */")
a(f"\t\t{resources_phase} /* Resources */ = {{")
a("\t\t\tisa = PBXResourcesBuildPhase;")
a("\t\t\tbuildActionMask = 2147483647;")
a("\t\t\tfiles = (")
a(f"\t\t\t\t{engines_build} /* Engines in Resources */,")
a("\t\t\t);")
a("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
a("\t\t};")
a("/* End PBXResourcesBuildPhase section */\n")

a("/* Begin PBXShellScriptBuildPhase section */")
a(f"\t\t{sign_engines_phase} /* Firmar motores incluidos */ = {{")
a("\t\t\tisa = PBXShellScriptBuildPhase;")
a("\t\t\talwaysOutOfDate = 1;")
a("\t\t\tbuildActionMask = 2147483647;")
a("\t\t\tfiles = ();")
a("\t\t\tinputPaths = (\"$(SRCROOT)/Resources/Engines/engines.json\");")
a("\t\t\tname = \"Firmar motores incluidos\";")
a("\t\t\toutputPaths = ();")
a("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
a("\t\t\tshellPath = /bin/bash;")
a("\t\t\tshellScript = \"\\\"${SRCROOT}/Scripts/sign_embedded_engines.sh\\\" \\\"${TARGET_BUILD_DIR}/${WRAPPER_NAME}\\\" \\\"${EXPANDED_CODE_SIGN_IDENTITY:-}\\\"\";")
a("\t\t};")
a("/* End PBXShellScriptBuildPhase section */\n")

a("/* Begin PBXSourcesBuildPhase section */")
a(f"\t\t{sources_phase} /* Sources */ = {{")
a("\t\t\tisa = PBXSourcesBuildPhase;")
a("\t\t\tbuildActionMask = 2147483647;")
a("\t\t\tfiles = (")
for path in source_files:
    a(f"\t\t\t\t{build_files[path]} /* {Path(path).name} in Sources */,")
a("\t\t\t);")
a("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
a("\t\t};")
a("/* End PBXSourcesBuildPhase section */\n")

a("/* Begin XCBuildConfiguration section */")
for config_id, name in [(project_debug, "Debug"), (project_release, "Release")]:
    a(f"\t\t{config_id} /* {name} */ = {{")
    a("\t\t\tisa = XCBuildConfiguration;")
    a("\t\t\tbuildSettings = {")
    a("\t\t\t\tCLANG_ENABLE_MODULES = YES;")
    a("\t\t\t\tMACOSX_DEPLOYMENT_TARGET = 14.0;")
    a("\t\t\t\tSDKROOT = macosx;")
    a("\t\t\t\tSWIFT_VERSION = 6.0;")
    if name == "Debug":
        a("\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = \"-Onone\";")
    else:
        a("\t\t\t\tSWIFT_COMPILATION_MODE = wholemodule;")
    a("\t\t\t};")
    a(f"\t\t\tname = {name};")
    a("\t\t};")

for config_id, name in [(target_debug, "Debug"), (target_release, "Release")]:
    a(f"\t\t{config_id} /* {name} */ = {{")
    a("\t\t\tisa = XCBuildConfiguration;")
    a("\t\t\tbuildSettings = {")
    a("\t\t\t\tARCHS = arm64;")
    a("\t\t\t\tCODE_SIGN_STYLE = Automatic;")
    a("\t\t\t\tCOMBINE_HIDPI_IMAGES = YES;")
    a("\t\t\t\tCURRENT_PROJECT_VERSION = 26;")
    a("\t\t\t\tENABLE_HARDENED_RUNTIME = YES;")
    a("\t\t\t\tGENERATE_INFOPLIST_FILE = YES;")
    a("\t\t\t\tINFOPLIST_KEY_CFBundleDisplayName = ZEUVE;")
    a("\t\t\t\tINFOPLIST_KEY_LSApplicationCategoryType = \"public.app-category.utilities\";")
    a("\t\t\t\tLD_RUNPATH_SEARCH_PATHS = \"$(inherited) @executable_path/../Frameworks\";")
    a("\t\t\t\tMACOSX_DEPLOYMENT_TARGET = 14.0;")
    a("\t\t\t\tMARKETING_VERSION = 0.7.5;")
    a("\t\t\t\tONLY_ACTIVE_ARCH = YES;")
    a("\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = com.zeuve.app;")
    a("\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";")
    a("\t\t\t\tSUPPORTED_PLATFORMS = macosx;")
    a("\t\t\t\tSWIFT_STRICT_CONCURRENCY = complete;")
    a("\t\t\t\tSWIFT_VERSION = 6.0;")
    a("\t\t\t};")
    a(f"\t\t\tname = {name};")
    a("\t\t};")
a("/* End XCBuildConfiguration section */\n")

a("/* Begin XCConfigurationList section */")
a(f"\t\t{project_config_list} /* Build configuration list for PBXProject \"ZEUVE\" */ = {{")
a("\t\t\tisa = XCConfigurationList;")
a(f"\t\t\tbuildConfigurations = ({project_debug} /* Debug */, {project_release} /* Release */);")
a("\t\t\tdefaultConfigurationIsVisible = 0;")
a("\t\t\tdefaultConfigurationName = Release;")
a("\t\t};")
a(f"\t\t{target_config_list} /* Build configuration list for PBXNativeTarget \"ZEUVE\" */ = {{")
a("\t\t\tisa = XCConfigurationList;")
a(f"\t\t\tbuildConfigurations = ({target_debug} /* Debug */, {target_release} /* Release */);")
a("\t\t\tdefaultConfigurationIsVisible = 0;")
a("\t\t\tdefaultConfigurationName = Release;")
a("\t\t};")
a("/* End XCConfigurationList section */\n")

a("/* Begin XCLocalSwiftPackageReference section */")
a(f"\t\t{package_ref} /* XCLocalSwiftPackageReference \".\" */ = {{")
a("\t\t\tisa = XCLocalSwiftPackageReference;")
a("\t\t\trelativePath = .;")
a("\t\t};")
a("/* End XCLocalSwiftPackageReference section */\n")

a("/* Begin XCSwiftPackageProductDependency section */")
for name in products:
    a(f"\t\t{product_deps[name]} /* {name} */ = {{")
    a("\t\t\tisa = XCSwiftPackageProductDependency;")
    a(f"\t\t\tproductName = {name};")
    a("\t\t};")
a("/* End XCSwiftPackageProductDependency section */\n")

a("\t};")
a(f"\trootObject = {project_id} /* Project object */;")
a("}")
PROJECT.write_text("\n".join(lines) + "\n")
print(f"Generated {PROJECT} with {len(source_files)} Swift app files")
