import Foundation

public enum OrganizerExtensionRules {
    public static let defaults: [String: ExtensionRule] = [
        "jpg": .init(category: "Imágenes", formatFolder: "JPG-JPEG"),
        "jpeg": .init(category: "Imágenes", formatFolder: "JPG-JPEG"),
        "png": .init(category: "Imágenes", formatFolder: "PNG"),
        "gif": .init(category: "Imágenes", formatFolder: "GIF"),
        "webp": .init(category: "Imágenes", formatFolder: "WEBP"),
        "heic": .init(category: "Imágenes", formatFolder: "HEIC-HEIF"),
        "heif": .init(category: "Imágenes", formatFolder: "HEIC-HEIF"),
        "tif": .init(category: "Imágenes", formatFolder: "TIFF-TIF"),
        "tiff": .init(category: "Imágenes", formatFolder: "TIFF-TIF"),
        "bmp": .init(category: "Imágenes", formatFolder: "BMP"),
        "svg": .init(category: "Imágenes", formatFolder: "SVG"),
        "ico": .init(category: "Imágenes", formatFolder: "ICO"),
        "raw": .init(category: "Imágenes", formatFolder: "RAW"),
        "dng": .init(category: "Imágenes", formatFolder: "RAW"),
        "cr2": .init(category: "Imágenes", formatFolder: "RAW"),
        "cr3": .init(category: "Imágenes", formatFolder: "RAW"),
        "nef": .init(category: "Imágenes", formatFolder: "RAW"),
        "arw": .init(category: "Imágenes", formatFolder: "RAW"),
        "raf": .init(category: "Imágenes", formatFolder: "RAW"),
        "orf": .init(category: "Imágenes", formatFolder: "RAW"),
        "mp4": .init(category: "Vídeos", formatFolder: "MP4"),
        "mov": .init(category: "Vídeos", formatFolder: "MOV"),
        "mkv": .init(category: "Vídeos", formatFolder: "MKV"),
        "avi": .init(category: "Vídeos", formatFolder: "AVI"),
        "webm": .init(category: "Vídeos", formatFolder: "WEBM"),
        "m4v": .init(category: "Vídeos", formatFolder: "M4V"),
        "wmv": .init(category: "Vídeos", formatFolder: "WMV"),
        "flv": .init(category: "Vídeos", formatFolder: "FLV"),
        "mpeg": .init(category: "Vídeos", formatFolder: "MPEG-MPG"),
        "mpg": .init(category: "Vídeos", formatFolder: "MPEG-MPG"),
        "3gp": .init(category: "Vídeos", formatFolder: "3GP"),
        "mp3": .init(category: "Audio", formatFolder: "MP3"),
        "wav": .init(category: "Audio", formatFolder: "WAV"),
        "m4a": .init(category: "Audio", formatFolder: "M4A"),
        "aac": .init(category: "Audio", formatFolder: "AAC"),
        "flac": .init(category: "Audio", formatFolder: "FLAC"),
        "ogg": .init(category: "Audio", formatFolder: "OGG"),
        "aif": .init(category: "Audio", formatFolder: "AIFF-AIF"),
        "aiff": .init(category: "Audio", formatFolder: "AIFF-AIF"),
        "wma": .init(category: "Audio", formatFolder: "WMA"),
        "mid": .init(category: "Audio", formatFolder: "MIDI-MID"),
        "midi": .init(category: "Audio", formatFolder: "MIDI-MID"),
        "pdf": .init(category: "Documentos", formatFolder: "PDF"),
        "doc": .init(category: "Documentos", formatFolder: "DOC-DOCX"),
        "docx": .init(category: "Documentos", formatFolder: "DOC-DOCX"),
        "xls": .init(category: "Documentos", formatFolder: "XLS-XLSX"),
        "xlsx": .init(category: "Documentos", formatFolder: "XLS-XLSX"),
        "ppt": .init(category: "Documentos", formatFolder: "PPT-PPTX"),
        "pptx": .init(category: "Documentos", formatFolder: "PPT-PPTX"),
        "odt": .init(category: "Documentos", formatFolder: "ODT"),
        "ods": .init(category: "Documentos", formatFolder: "ODS"),
        "odp": .init(category: "Documentos", formatFolder: "ODP"),
        "pages": .init(category: "Documentos", formatFolder: "PAGES"),
        "numbers": .init(category: "Documentos", formatFolder: "NUMBERS"),
        "key": .init(category: "Documentos", formatFolder: "KEYNOTE"),
        "txt": .init(category: "Documentos", formatFolder: "TXT"),
        "rtf": .init(category: "Documentos", formatFolder: "RTF"),
        "md": .init(category: "Documentos", formatFolder: "MARKDOWN"),
        "epub": .init(category: "Documentos", formatFolder: "EPUB"),
        "mobi": .init(category: "Documentos", formatFolder: "MOBI"),
        "csv": .init(category: "Datos", formatFolder: "CSV"),
        "tsv": .init(category: "Datos", formatFolder: "TSV"),
        "sql": .init(category: "Datos", formatFolder: "SQL"),
        "db": .init(category: "Datos", formatFolder: "DB-SQLITE"),
        "sqlite": .init(category: "Datos", formatFolder: "DB-SQLITE"),
        "sqlite3": .init(category: "Datos", formatFolder: "DB-SQLITE"),
        "zip": .init(category: "Comprimidos", formatFolder: "ZIP"),
        "rar": .init(category: "Comprimidos", formatFolder: "RAR"),
        "7z": .init(category: "Comprimidos", formatFolder: "7Z"),
        "tar": .init(category: "Comprimidos", formatFolder: "TAR"),
        "gz": .init(category: "Comprimidos", formatFolder: "GZ"),
        "bz2": .init(category: "Comprimidos", formatFolder: "BZ2"),
        "xz": .init(category: "Comprimidos", formatFolder: "XZ"),
        "dmg": .init(category: "Aplicaciones e instaladores", formatFolder: "DMG"),
        "pkg": .init(category: "Aplicaciones e instaladores", formatFolder: "PKG"),
        "iso": .init(category: "Aplicaciones e instaladores", formatFolder: "ISO"),
        "py": .init(category: "Código", formatFolder: "PYTHON"),
        "js": .init(category: "Código", formatFolder: "JAVASCRIPT"),
        "jsx": .init(category: "Código", formatFolder: "JAVASCRIPT"),
        "ts": .init(category: "Código", formatFolder: "TYPESCRIPT"),
        "tsx": .init(category: "Código", formatFolder: "TYPESCRIPT"),
        "html": .init(category: "Código", formatFolder: "HTML-HTM"),
        "htm": .init(category: "Código", formatFolder: "HTML-HTM"),
        "css": .init(category: "Código", formatFolder: "CSS"),
        "scss": .init(category: "Código", formatFolder: "SCSS-SASS"),
        "sass": .init(category: "Código", formatFolder: "SCSS-SASS"),
        "json": .init(category: "Código", formatFolder: "JSON"),
        "xml": .init(category: "Código", formatFolder: "XML"),
        "yaml": .init(category: "Código", formatFolder: "YAML-YML"),
        "yml": .init(category: "Código", formatFolder: "YAML-YML"),
        "java": .init(category: "Código", formatFolder: "JAVA"),
        "c": .init(category: "Código", formatFolder: "C-C++"),
        "h": .init(category: "Código", formatFolder: "C-C++"),
        "cpp": .init(category: "Código", formatFolder: "C-C++"),
        "hpp": .init(category: "Código", formatFolder: "C-C++"),
        "swift": .init(category: "Código", formatFolder: "SWIFT"),
        "php": .init(category: "Código", formatFolder: "PHP"),
        "rb": .init(category: "Código", formatFolder: "RUBY"),
        "sh": .init(category: "Código", formatFolder: "SHELL"),
        "command": .init(category: "Código", formatFolder: "SHELL"),
        "psd": .init(category: "Diseño", formatFolder: "PHOTOSHOP-PSD"),
        "ai": .init(category: "Diseño", formatFolder: "ILLUSTRATOR-AI"),
        "indd": .init(category: "Diseño", formatFolder: "INDESIGN-INDD"),
        "sketch": .init(category: "Diseño", formatFolder: "SKETCH"),
        "fig": .init(category: "Diseño", formatFolder: "FIGMA-FIG"),
        "eps": .init(category: "Diseño", formatFolder: "EPS"),
        "dwg": .init(category: "Diseño", formatFolder: "AUTOCAD-DWG-DXF"),
        "dxf": .init(category: "Diseño", formatFolder: "AUTOCAD-DWG-DXF"),
        "ttf": .init(category: "Fuentes", formatFolder: "TTF"),
        "otf": .init(category: "Fuentes", formatFolder: "OTF"),
        "woff": .init(category: "Fuentes", formatFolder: "WOFF-WOFF2"),
        "woff2": .init(category: "Fuentes", formatFolder: "WOFF-WOFF2")
    ]

    public static func merged(with custom: [String: ExtensionRule]) -> [String: ExtensionRule] {
        var values = defaults
        for (extensionName, rule) in custom {
            values[extensionName.trimmingCharacters(in: CharacterSet(charactersIn: ".")).lowercased()] = rule
        }
        return values
    }

    public static func classify(_ url: URL, custom: [String: ExtensionRule] = [:]) -> ExtensionRule {
        let extensionName = url.pathExtension.lowercased()
        guard !extensionName.isEmpty else {
            return ExtensionRule(category: "Otros", formatFolder: organizerNoExtensionFolder)
        }
        return merged(with: custom)[extensionName]
            ?? ExtensionRule(category: "Otros", formatFolder: extensionName.uppercased())
    }
}
